# /etc/sysctl.d/99-docker.conf
#
# Tekijä: Jesse Karnavaara
# Vuosi: 2026
# Tarkoitus: Määrittää Linux-ytimen (kernel) parametrit vastaamaan Codebased Oy:n
#            kehitysinfran ja Docker-sovelluksen vaatimuksia.
#
# Huomiot konfiguraatiosta ja CIS-poikkeuksista:
# - Docker ja reititys (ip_forward): CIS Benchmark suosittelee oletuksena arvoa 0 
#   (Control: Ensure IP forwarding is disabled). Tämä on kuitenkin pakko asettaa 
#   arvoon 1 (päälle), jotta Dockerin virtuaaliverkot voivat reitittää liikennettä 
#   konttien välillä ja isäntäkoneesta ulospäin. Tämä on hyväksytty poikkeus.
#
# Verifiointi:
#   Aja 'sudo sysctl --system' ladataksesi asetukset uudelleen.
#   Tarkista yksittäinen arvo: 'sysctl net.ipv4.ip_forward'
#

net.ipv4.ip_forward=1